name: Build Linux ARM64 Release

# Trigger manually or on version tags
on:
  push:
    tags:
      - 'v*'  # Only run on version tags like v2.0.0, v2.1.0, etc.
  workflow_dispatch:  # Allows manual trigger from GitHub UI
    inputs:
      branch:
        description: 'Branch to build'
        required: false
        default: 'ImageDescriber'

jobs:
  build-arm64:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.inputs.branch || github.ref }}
    
    - name: Set up QEMU for ARM64 emulation
      uses: docker/setup-qemu-action@v3
      with:
        platforms: linux/arm64
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build in ARM64 container
      run: |
        docker run --rm --platform linux/arm64 \
          -v ${{ github.workspace }}:/workspace \
          -w /workspace \
          python:3.11-slim bash -c "
            set -e
            echo '=== Installing system dependencies ==='
            apt-get update
            apt-get install -y gcc g++ make binutils
            
            echo '=== Installing Python dependencies ==='
            pip install --upgrade pip
            pip install -r requirements.txt
            pip install pyinstaller
            
            echo '=== Python and PyInstaller versions ==='
            python --version
            pyinstaller --version
            uname -m
            
            echo '=== Building IDT ==='
            pyinstaller idt_cli.py \
              --name idt \
              --onefile \
              --add-data 'scripts:scripts' \
              --add-data 'analysis:analysis' \
              --hidden-import=PIL \
              --hidden-import=anthropic \
              --hidden-import=openai \
              --hidden-import=ollama
            
            echo '=== Creating release directory ==='
            mkdir -p release
            
            echo '=== Packaging IDT ==='
            cd dist
            zip -r ../release/idt_linux_arm64.zip idt
            cd ..
            
            echo '=== Build complete ==='
            ls -lh release/
          "
    
    - name: Verify build output
      run: |
        echo "=== Build Artifacts ==="
        ls -lh release/
        file dist/idt || echo "IDT binary not found"
    
    - name: Upload IDT ARM64 release
      uses: actions/upload-artifact@v4
      with:
        name: idt-linux-arm64
        path: release/idt_linux_arm64.zip
        if-no-files-found: error
    
    - name: Build Summary
      run: |
        echo "=== Build Complete ==="
        echo "Platform: Linux ARM64"
        echo "Branch: ${{ github.event.inputs.branch || github.ref_name }}"
        echo "Commit: ${{ github.sha }}"
        echo ""
        echo "Download artifacts from the Actions tab"
