name: Build Windows AMD64 Release

# Trigger manually or on version tags
on:
  push:
    tags:
      - 'v*'  # Only run on version tags like v2.0.0, v2.1.0, etc.
  workflow_dispatch:  # Allows manual trigger from GitHub UI
    inputs:
      branch:
        description: 'Branch to build'
        required: false
        default: 'ImageDescriber'

jobs:
  build-windows:
    runs-on: windows-latest  # Windows Server 2022 AMD64
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.inputs.branch || github.ref }}
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
      shell: cmd
    
    - name: Display Python and PyInstaller versions
      run: |
        python --version
        pyinstaller --version
      shell: cmd
    
    - name: Build all applications
      run: |
        call builditall.bat
      shell: cmd
      
    - name: Package all applications
      run: |
        call packageitall.bat
      shell: cmd
    
    - name: List release files
      run: |
        echo "=== Release Directory Contents ==="
        dir release /s
      shell: cmd
    
    - name: Upload IDT release
      uses: actions/upload-artifact@v4
      with:
        name: idt-windows-amd64
        path: release/ImageDescriptionToolkit_v*.zip
        if-no-files-found: error
    
    - name: Upload Viewer release
      uses: actions/upload-artifact@v4
      with:
        name: viewer-windows-amd64
        path: viewer/viewer_releases/viewer_v*_amd64.zip
        if-no-files-found: warn
    
    - name: Upload Prompt Editor release
      uses: actions/upload-artifact@v4
      with:
        name: prompteditor-windows-amd64
        path: prompt_editor/prompt_editor_releases/prompt_editor_v*_amd64.zip
        if-no-files-found: warn
    
    - name: Upload ImageDescriber release
      uses: actions/upload-artifact@v4
      with:
        name: imagedescriber-windows-amd64
        path: imagedescriber/imagedescriber_releases/imagedescriber_v*_amd64.zip
        if-no-files-found: warn
    
    - name: Build Summary
      run: |
        echo "=== Build Complete ==="
        echo "Branch: ${{ github.event.inputs.branch || github.ref_name }}"
        echo "Commit: ${{ github.sha }}"
        echo ""
        echo "Download artifacts from the Actions tab"
      shell: cmd
